import {
  icfy,
  icfyAI,
  icfyC,
  icfyGAMING,
  icfyGITHUB,
  icfyHTML,
  icfyJAVA,
  icfyJS,
  icfyPHP,
  icfyPYTHON,
  icfyREACT,
  icfyRUST,
  icfySOL,
  icfySQL,
  icfyTS,
} from "icones";

export const ENUMS_FEATURE_TYPE = ["New Feature", "Bug", "Improvement"];

export const ENUMS = {
  languagesLevel: ["Notions", "Courant", "Professionnel", "Langue maternelle"],
  courts: [
    { badge: icfy.ux.admin, court: "Centralized" },
    { badge: icfyGITHUB, court: "Kleros" },
    { badge: icfyREACT, court: "React" },
    { badge: icfyPYTHON, court: "Python" },
    { badge: icfy.technos.nodeJS, court: "NodeJS" },
    { badge: icfySOL, court: "Solidity" },
    { badge: icfyJAVA, court: "Java" },
    { badge: icfyC, court: "C++" },
    { badge: icfy.technos.csharp, court: "CSharp" },
    { badge: icfy.technos.go, court: "Go" },
    { badge: icfyRUST, court: "Rust" },
    { badge: icfy.technos.ruby, court: "Ruby" },
    { badge: icfyPHP, court: "PHP" },
    { badge: icfy.technos.swift, court: "Swift" },
    { badge: icfy.technos.kotlin, court: "Kotlin" },
    { badge: icfy.technos.dart, court: "Dart" },
    { badge: icfy.technos.scala, court: "Scala" },
    { badge: icfy.technos.haskell, court: "Haskell" },
    { badge: icfy.technos.lua, court: "Lua" },
    { badge: icfyJS, court: "JavaScript" },
    { badge: icfyTS, court: "TypeScript" },
    { badge: icfy.technos.coffeScript, court: "CoffeScript" },
    { badge: icfy.technos.shell, court: "Shell" },
    { badge: icfySQL, court: "SQL" },
    { badge: icfyHTML, court: "HTML" },
  ],
  domain: [
    {
      name: "enterprise",
      color: "info",
      icon: icfy.domain.enterprise,
    },
    {
      name: "frontend",
      color: "warning",
      icon: icfy.domain.frontend,
    },
    {
      name: "backend",
      color: "info",
      icon: icfy.domain.backend,
    },
    {
      name: "web3",
      color: "warning",
      icon: icfy.domain.blockchain,
    },
    {
      name: "gaming",
      color: "secondary",
      icon: icfy.domain.gaming,
    },
    {
      name: "ai",
      color: "success",
      icon: icfy.domain.ai,
    },
    {
      name: "designer",
      color: "error",
      icon: icfy.domain.designer,
    },
  ],
  experience: [
    {
      name: "junior",
      color: "magenta",
      icon: icfy.domain.frontend,
    },
    {
      name: "middle",
      color: "magenta",
      icon: icfy.domain.backend,
    },
    {
      name: "senior",
      color: "magenta",
      icon: icfy.domain.blockchain,
    },
  ],
  feature: {},
};
